### ISSUE TITLE
Pairing Required durumu

### ISSUE THREAD

**Issue by burakgokcinarr** [ersinayaz/rn-samsung-tv-remote#3]
Merhabalar öncelikle elinize sağlık. Fakat cihaza bağlantı yaptığımda "Pairing Required" hatası alıyorum. TV samsung 2018 model.
TV'imde de herhangi bir eşleşme mesajı alamıyorum.

const tv = new SamsungRemote({ ip: "192.168.1.55"});
tv.init(); 

//await tv.requestPin();
//const identity = await tv.confirmPin("1234")
//tv.init(identity); 

await tv.connect()

yukarıda yaptığım kod var acaba nerede yanlış yapıyorum ?

**Comment by ersinayaz** [comment]
Merhaba,
await tv.requestPin(); satırını yorumlanmış olarak görüyorum. 
Test aşamasında bu fonksiyonu kullanıyor musunuz?

**Comment by ersinayaz** [comment]
The issue has been closed due to no response.
