### ISSUE TITLE
handleEvent : unable to decrypt data [RangeError: length cannot be negative]

### ISSUE THREAD

**Issue by rajgopalv** [ersinayaz/rn-samsung-tv-remote#4]
on `tv.connect()`, i'm, getting the following error on my console. 
```LOG  handleEvent : unable to decrypt data [RangeError: length cannot be negative]```

This is my code, A fresh new Expo project, and this is what my App.js looks like 
https://gist.github.com/rajgopalv/f7ddf40d4365f11871c5fd0d8e997116

**Comment by ersinayaz** [comment]
Hi,
Can you share your TV model please?

**Comment by ersinayaz** [comment]
The issue has been closed due to no response.
